# Generated by Django 3.1.4 on 2021-01-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20210109_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default='2021-01-0909:58:26'),
        ),
    ]
