# Generated by Django 3.1.4 on 2021-01-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210109_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default='2021-01-09'),
        ),
    ]
