# Generated by Django 3.1.4 on 2021-01-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20210110_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_emails',
            field=models.BooleanField(default=True),
        ),
    ]
